// Code generated by protoc-gen-go. DO NOT EDIT.
// source: print.proto

package protoc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrintRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrintRequest) Reset()         { *m = PrintRequest{} }
func (m *PrintRequest) String() string { return proto.CompactTextString(m) }
func (*PrintRequest) ProtoMessage()    {}
func (*PrintRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bf5a1e5cdf07e43, []int{0}
}

func (m *PrintRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrintRequest.Unmarshal(m, b)
}
func (m *PrintRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrintRequest.Marshal(b, m, deterministic)
}
func (m *PrintRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrintRequest.Merge(m, src)
}
func (m *PrintRequest) XXX_Size() int {
	return xxx_messageInfo_PrintRequest.Size(m)
}
func (m *PrintRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrintRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrintRequest proto.InternalMessageInfo

func (m *PrintRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PrintReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrintReply) Reset()         { *m = PrintReply{} }
func (m *PrintReply) String() string { return proto.CompactTextString(m) }
func (*PrintReply) ProtoMessage()    {}
func (*PrintReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bf5a1e5cdf07e43, []int{1}
}

func (m *PrintReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrintReply.Unmarshal(m, b)
}
func (m *PrintReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrintReply.Marshal(b, m, deterministic)
}
func (m *PrintReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrintReply.Merge(m, src)
}
func (m *PrintReply) XXX_Size() int {
	return xxx_messageInfo_PrintReply.Size(m)
}
func (m *PrintReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PrintReply.DiscardUnknown(m)
}

var xxx_messageInfo_PrintReply proto.InternalMessageInfo

func (m *PrintReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PrintRequest)(nil), "protoc.PrintRequest")
	proto.RegisterType((*PrintReply)(nil), "protoc.PrintReply")
}

func init() { proto.RegisterFile("print.proto", fileDescriptor_4bf5a1e5cdf07e43) }

var fileDescriptor_4bf5a1e5cdf07e43 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0xcc,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc9, 0x52, 0x32, 0xe9, 0xf9,
	0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x89, 0x05, 0x99, 0xfa, 0x89, 0x79, 0x79, 0xf9, 0x25, 0x89, 0x25,
	0x99, 0xf9, 0x79, 0xc5, 0x10, 0x55, 0x4a, 0x4a, 0x5c, 0x3c, 0x01, 0x20, 0x4d, 0x41, 0xa9, 0x85,
	0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x1a, 0x17, 0x17, 0x54, 0x4d, 0x41, 0x4e, 0xa5, 0x90, 0x04,
	0x17, 0x7b, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x3a, 0x4c, 0x11, 0x8c, 0x6b, 0x14, 0xcf, 0xc5, 0xe3,
	0x9e, 0x58, 0x92, 0x5a, 0x9e, 0x58, 0x09, 0x56, 0x2e, 0xe4, 0xcf, 0xc5, 0x0a, 0x61, 0x88, 0x40,
	0x2c, 0x4b, 0xd6, 0x43, 0xb6, 0x4a, 0x4a, 0x08, 0x4d, 0xb4, 0x20, 0xa7, 0x52, 0x49, 0xa6, 0xe9,
	0xf2, 0x93, 0xc9, 0x4c, 0x62, 0x4a, 0x82, 0xfa, 0x65, 0x86, 0xfa, 0xa9, 0x15, 0x89, 0xb9, 0x05,
	0x39, 0xa9, 0xfa, 0x60, 0x5f, 0x59, 0x31, 0x6a, 0x25, 0x41, 0xbc, 0x64, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0xc0, 0xc7, 0xc8, 0x8b, 0xe8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GatewayPrintClient is the client API for GatewayPrint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayPrintClient interface {
	Print(ctx context.Context, in *PrintRequest, opts ...grpc.CallOption) (*PrintReply, error)
}

type gatewayPrintClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayPrintClient(cc grpc.ClientConnInterface) GatewayPrintClient {
	return &gatewayPrintClient{cc}
}

func (c *gatewayPrintClient) Print(ctx context.Context, in *PrintRequest, opts ...grpc.CallOption) (*PrintReply, error) {
	out := new(PrintReply)
	err := c.cc.Invoke(ctx, "/protoc.GatewayPrint/Print", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayPrintServer is the server API for GatewayPrint service.
type GatewayPrintServer interface {
	Print(context.Context, *PrintRequest) (*PrintReply, error)
}

// UnimplementedGatewayPrintServer can be embedded to have forward compatible implementations.
type UnimplementedGatewayPrintServer struct {
}

func (*UnimplementedGatewayPrintServer) Print(ctx context.Context, req *PrintRequest) (*PrintReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Print not implemented")
}

func RegisterGatewayPrintServer(s *grpc.Server, srv GatewayPrintServer) {
	s.RegisterService(&_GatewayPrint_serviceDesc, srv)
}

func _GatewayPrint_Print_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayPrintServer).Print(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoc.GatewayPrint/Print",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayPrintServer).Print(ctx, req.(*PrintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GatewayPrint_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protoc.GatewayPrint",
	HandlerType: (*GatewayPrintServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Print",
			Handler:    _GatewayPrint_Print_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "print.proto",
}
